// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zawknmbrugqkougnsjkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inphd2tubWJydWdxa291Z25zamtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzODcyMjIsImV4cCI6MjA2Njk2MzIyMn0.ROZhqYAKoC3wCVnaVuKbYXhffoUCbED3jcvgw_Ue0fM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});